#####################
# ARM ALARM IF AWAY #
#####################
- alias: Arm alarm if away
  trigger:
  - platform: state
    entity_id: binary_sensor.away_mode
    from: 'off'
    to: 'on'
  action:
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.ha_alarm 
  mode: restart

############################
# DISARM ALARM IF GOT HOME #
############################
- alias: Disarm alarm if got home
  trigger:
  - platform: state
    entity_id: binary_sensor.away_mode
    from: 'on'
    to: 'off'
  action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.ha_alarm 
    data:
      code: !secret alarm_code
  mode: restart

################
# TRIGGER AWAY #
################
- alias: Trigger alarm away
  trigger:
  - platform: state
    entity_id: group.open_sensor
    from: 'off'
    to: 'on'
  condition: 
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: armed_away
  action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.ha_alarm
  - service: notify.notify
    data:
      message: 'Alarme déclenchée'
  mode: restart
  
################
# TRIGGER HOME #
################
- alias: Trigger alarm away
  trigger:
  - platform: state
    entity_id: group.open_sensor
    from: 'off'
    to: 'on'
  condition: 
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: armed_home
  action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.ha_alarm
  - service: notify.notify
    data:
      message: 'Alarme déclenchée'
  mode: restart

###################
# SIREN AND FLASH #
###################

# trigger start
- alias: Alarm triggered
  trigger:
  - platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: 'triggered'
  action:
  - service: script.turn_on
    entity_id: script.flash_bureau
  - service: switch.turn_on
    entity_id: switch.aeon_siren
      
# alarm is disarmed
- alias: Alarm disarmed
  trigger:
  - platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: 'disarmed'
  action:
  - service: script.turn_off
    entity_id: script.flash_bureau
  - service: light.turn_off
    entity_id: light.bureau_color
  - service: switch.turn_off
    entity_id: switch.aeon_siren
